### ISSUE TITLE
can you please add a license? 

### ISSUE THREAD

**Issue by kasandrop** [ali-bouali/springboot-3-micro-service-demo#2]
want to express my gratitude for the work you've done with the code. It has been incredibly helpful in bringing my project to life. However, I noticed that you didn't include a license with it. I would like to ensure that I can submit my code as a university project without any legal issues. 

Therefore, I kindly request that you add a license to your work. Thank you for understanding! Without your license, I will not be able to submit my code."

**Comment by ali-bouali** [comment]
Hello,
I hope my response is not too late.
I will add a licence to the repo.
